risk:
  terms:
    - Hémoglobine A1C
    - Microalbumine
    - Taille
    - Poids
    - Fumeur
    - Fumeuse
    - Anormal
    - Cholestérol
    - Vertiges
    - Rechute
    - Réaction
    - Anticorps