spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: patients
          uri: ${PATIENT_URI:http://localhost:9001}
          predicates:
            - Path=/v1/api/patients/**

        - id: notes
          uri: ${NOTE_URI:http://localhost:9002}
          predicates:
            - Path=/v1/api/notes/**

        - id: risk
          uri: ${RISK_URI:http://localhost:9003}
          predicates:
            - Path=/v1/api/risk/**

server:
  port: 8888
